const ORDER_STATUS = {
  PENDING: "pending",
  CONFIRMED: "confirmed",
  PROCESSING: "processing",
  MANUFACTURING: "manufacturing",
  RECEIVED: "received",
  PACKED: "packed",
  SHIPPED: "shipped",
  DELIVERED: "delivered",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  RETURN_REQUESTED: "return_requested",
  RETURNED: "returned",
  REFUNDED: "refunded",
};

const OPS_VISIBLE_STATUSES = [
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PROCESSING,
  ORDER_STATUS.MANUFACTURING,
  ORDER_STATUS.RECEIVED,
  ORDER_STATUS.PACKED,
  ORDER_STATUS.SHIPPED,
];

const OPS_LIST_FILTERABLE_STATUSES = [
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PROCESSING,
];

/**
 * Transition hợp lệ cho từng order_type qua endpoint PUT /orders/:id/status.
 *
 * QUAN TRỌNG:
 *  - "return_requested" chỉ được set bởi return.service.requestReturn (không qua endpoint này).
 *  - "returned" và "refunded" chỉ được set bởi return.service.completeReturn / rejectReturn (transaction).
 *  → KHÔNG được xuất hiện trong bảng transition này để tránh bypass luồng ReturnRequest.
 */
const ORDER_TRANSITIONS = {
  stock: {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.PACKED, ORDER_STATUS.SHIPPED],
    [ORDER_STATUS.PACKED]: [ORDER_STATUS.SHIPPED],
    [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.DELIVERED],
    [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
    [ORDER_STATUS.COMPLETED]: [],
    [ORDER_STATUS.CANCELLED]: [],
    [ORDER_STATUS.RETURN_REQUESTED]: [],
    [ORDER_STATUS.RETURNED]: [],
    [ORDER_STATUS.REFUNDED]: [],
  },
  prescription: {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.MANUFACTURING],
    [ORDER_STATUS.MANUFACTURING]: [ORDER_STATUS.PACKED],
    [ORDER_STATUS.PACKED]: [ORDER_STATUS.SHIPPED],
    [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.DELIVERED],
    [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
    [ORDER_STATUS.COMPLETED]: [],
    [ORDER_STATUS.CANCELLED]: [],
    [ORDER_STATUS.RETURN_REQUESTED]: [],
    [ORDER_STATUS.RETURNED]: [],
    [ORDER_STATUS.REFUNDED]: [],
  },
  pre_order: {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.RECEIVED],
    [ORDER_STATUS.RECEIVED]: [ORDER_STATUS.PACKED],
    [ORDER_STATUS.PACKED]: [ORDER_STATUS.SHIPPED],
    [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.DELIVERED],
    [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
    [ORDER_STATUS.COMPLETED]: [],
    [ORDER_STATUS.CANCELLED]: [],
    [ORDER_STATUS.RETURN_REQUESTED]: [],
    [ORDER_STATUS.RETURNED]: [],
    [ORDER_STATUS.REFUNDED]: [],
  },
};

const OPS_ONLY_STATUSES = [
  ORDER_STATUS.PROCESSING,
  ORDER_STATUS.MANUFACTURING,
  ORDER_STATUS.RECEIVED,
  ORDER_STATUS.PACKED,
  ORDER_STATUS.SHIPPED,
  ORDER_STATUS.DELIVERED,
];

const INVENTORY_PLACEMENT = {
  RESERVED_ONLY: "reserved_only",
  IMMEDIATE_STOCK: "immediate_stock",
};

module.exports = {
  ORDER_STATUS,
  OPS_VISIBLE_STATUSES,
  OPS_LIST_FILTERABLE_STATUSES,
  ORDER_TRANSITIONS,
  OPS_ONLY_STATUSES,
  INVENTORY_PLACEMENT,
};

